language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: x71bscqB0HKejt+8YwfBQPyPWRDBkqUvbR8Srt2WxgiiKokCxWrdMskNsP4PhAqgrVsY3TyC0YCqWGlUpTEjeO+VLNU1Av+Z8xxgK9x69h8N1GbcuvjQeOgxst8We+QDm7jaEnFB/7ZbZoS+FJmfTp/XYy7dMxCb/v1hgCX1KIK3AYxhRlm0LdyrrKXJFgZnYay6vtMfbUY4SS9ip/X4VjB0vq8CfEKww3fbRtw4604Sk6F5UmLEpdi1r84BpOuK2nj5EwWEPGQnUWNYlX/h+hZe5ncGP2HB/QrBsvEpmvtzzwnm+p/tuWzt0TRuai5AIobKpjPpiDZTEZ8YrFceeM7SL3zosT9qiDPh4mCnIT3QZUv2TQEZWnCHBTt8Tj3NPJVkm5QLigN4XFBlWvBpyj4ljaQCuhvY31iihr8ifH4rRcYnZcYy0/l5OdAcKhZTj1YSzvmSPfUZMl/ZYQ7g/iJgMlfY84UACDoZU28SJHJXe265EPP0dArE10OwE+K8yrhNPLLDjmgrFBDf2U7OpeUI1/2j4H3ws5Vd4UQmmGt/R+svegBIt3CtDGPrUlskkEWlQzp/7vt1ZePsOafjs3WAePXrR2CM4OE3cpd7i3TJrQszZgin66dBOfpejKE2sXXHa+BNfyXSyqPI3qL2VtP8qCrV1EsFM7faULEpBGU=
  app: viewing-party-bdj
  on:
    repo: jakeheft/viewing_party
